weighted = true

raw_dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Deliverable_20240809"

[00-preprocess]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/00-preprocess"

[01-taz_spatial_join]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/01-taz_spatial_join"
hh_filename = "hh-taz_spatial_join.csv"
person_filename = "person-taz_spatial_join.csv"
trip_filename = "trip-taz_spatial_join.csv"

[02a-reformat]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/02-reformat"
hh_filename = "hh-reformat.csv"
person_filename = "person-reformat.csv"
trip_filename = "trip-reformat.csv"

