weighted = true

day_filename = "day.csv"
hh_filename = "hh.csv"
location_filename = "location.csv"
person_filename = "person.csv"
trip_filename = "trip.csv"
vehicle_filename = "vehicle.csv"

[raw]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Deliverable_20240809"

# TODO have a utils.py that generates the dirs for each step from
# Path(processed_dir) / subdir
# processed_dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809"

[00-preprocess]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/00-preprocess"

[01-taz_spatial_join]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/01-taz_spatial_join"
maz_filepath = "Q:/GIS/Model/MAZ/MAZ40051.shp"

[02a-reformat]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/02a-reformat"

[02b-link_trips_week]
dir = "Q:/Data/Surveys/HouseholdSurveys/MTC-SFCTA2022/Processed_20240809/02b-link_trips_week"
accegr_filename = "accegr_week.csv"  # access/egress
# CH: originally named "temp_tripx_linked_detail_week"; not sure what's in here nor what it's used for
trip_linked_detail_week_filename = "trip-detail.csv"